// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: extractor.proto
// Protobuf C++ Version: 6.30.0

#ifndef extractor_2eproto_2epb_2eh
#define extractor_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/empty.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_extractor_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_extractor_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_extractor_2eproto;
}  // extern "C"
namespace extractor {
class AllDataResponse;
struct AllDataResponseDefaultTypeInternal;
extern AllDataResponseDefaultTypeInternal _AllDataResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AllDataResponse_class_data_;
class FlightRow;
struct FlightRowDefaultTypeInternal;
extern FlightRowDefaultTypeInternal _FlightRow_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FlightRow_class_data_;
class PesquisaRow;
struct PesquisaRowDefaultTypeInternal;
extern PesquisaRowDefaultTypeInternal _PesquisaRow_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PesquisaRow_class_data_;
class ReservaRow;
struct ReservaRowDefaultTypeInternal;
extern ReservaRowDefaultTypeInternal _ReservaRow_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ReservaRow_class_data_;
}  // namespace extractor
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace extractor {

// ===================================================================


// -------------------------------------------------------------------

class ReservaRow final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:extractor.ReservaRow) */ {
 public:
  inline ReservaRow() : ReservaRow(nullptr) {}
  ~ReservaRow() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ReservaRow* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ReservaRow));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ReservaRow(::google::protobuf::internal::ConstantInitialized);

  inline ReservaRow(const ReservaRow& from) : ReservaRow(nullptr, from) {}
  inline ReservaRow(ReservaRow&& from) noexcept
      : ReservaRow(nullptr, std::move(from)) {}
  inline ReservaRow& operator=(const ReservaRow& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReservaRow& operator=(ReservaRow&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReservaRow& default_instance() {
    return *reinterpret_cast<const ReservaRow*>(
        &_ReservaRow_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ReservaRow& a, ReservaRow& b) { a.Swap(&b); }
  inline void Swap(ReservaRow* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReservaRow* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReservaRow* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ReservaRow>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReservaRow& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ReservaRow& from) { ReservaRow::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ReservaRow* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "extractor.ReservaRow"; }

 protected:
  explicit ReservaRow(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ReservaRow(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ReservaRow& from);
  ReservaRow(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ReservaRow&& from) noexcept
      : ReservaRow(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTipoQuartoFieldNumber = 1,
    kNomeHotelFieldNumber = 2,
    kCidadeDestinoFieldNumber = 3,
    kNumeroQuartoFieldNumber = 4,
    kQuantidadePessoasFieldNumber = 5,
    kPrecoFieldNumber = 6,
    kOcupadoFieldNumber = 7,
    kDataIdaDiaFieldNumber = 8,
    kDataIdaMesFieldNumber = 9,
    kDataIdaAnoFieldNumber = 10,
  };
  // string tipo_quarto = 1;
  void clear_tipo_quarto() ;
  const std::string& tipo_quarto() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_tipo_quarto(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_tipo_quarto();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_tipo_quarto();
  void set_allocated_tipo_quarto(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_tipo_quarto() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_tipo_quarto(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_tipo_quarto();

  public:
  // string nome_hotel = 2;
  void clear_nome_hotel() ;
  const std::string& nome_hotel() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_nome_hotel(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_nome_hotel();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_nome_hotel();
  void set_allocated_nome_hotel(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_nome_hotel() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nome_hotel(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_nome_hotel();

  public:
  // string cidade_destino = 3;
  void clear_cidade_destino() ;
  const std::string& cidade_destino() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cidade_destino(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_cidade_destino();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_cidade_destino();
  void set_allocated_cidade_destino(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_cidade_destino() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cidade_destino(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_cidade_destino();

  public:
  // int32 numero_quarto = 4;
  void clear_numero_quarto() ;
  ::int32_t numero_quarto() const;
  void set_numero_quarto(::int32_t value);

  private:
  ::int32_t _internal_numero_quarto() const;
  void _internal_set_numero_quarto(::int32_t value);

  public:
  // int32 quantidade_pessoas = 5;
  void clear_quantidade_pessoas() ;
  ::int32_t quantidade_pessoas() const;
  void set_quantidade_pessoas(::int32_t value);

  private:
  ::int32_t _internal_quantidade_pessoas() const;
  void _internal_set_quantidade_pessoas(::int32_t value);

  public:
  // float preco = 6;
  void clear_preco() ;
  float preco() const;
  void set_preco(float value);

  private:
  float _internal_preco() const;
  void _internal_set_preco(float value);

  public:
  // bool ocupado = 7;
  void clear_ocupado() ;
  bool ocupado() const;
  void set_ocupado(bool value);

  private:
  bool _internal_ocupado() const;
  void _internal_set_ocupado(bool value);

  public:
  // int32 data_ida_dia = 8;
  void clear_data_ida_dia() ;
  ::int32_t data_ida_dia() const;
  void set_data_ida_dia(::int32_t value);

  private:
  ::int32_t _internal_data_ida_dia() const;
  void _internal_set_data_ida_dia(::int32_t value);

  public:
  // int32 data_ida_mes = 9;
  void clear_data_ida_mes() ;
  ::int32_t data_ida_mes() const;
  void set_data_ida_mes(::int32_t value);

  private:
  ::int32_t _internal_data_ida_mes() const;
  void _internal_set_data_ida_mes(::int32_t value);

  public:
  // int32 data_ida_ano = 10;
  void clear_data_ida_ano() ;
  ::int32_t data_ida_ano() const;
  void set_data_ida_ano(::int32_t value);

  private:
  ::int32_t _internal_data_ida_ano() const;
  void _internal_set_data_ida_ano(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:extractor.ReservaRow)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 10,
                                   0, 72,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ReservaRow& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr tipo_quarto_;
    ::google::protobuf::internal::ArenaStringPtr nome_hotel_;
    ::google::protobuf::internal::ArenaStringPtr cidade_destino_;
    ::int32_t numero_quarto_;
    ::int32_t quantidade_pessoas_;
    float preco_;
    bool ocupado_;
    ::int32_t data_ida_dia_;
    ::int32_t data_ida_mes_;
    ::int32_t data_ida_ano_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_extractor_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ReservaRow_class_data_;
// -------------------------------------------------------------------

class PesquisaRow final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:extractor.PesquisaRow) */ {
 public:
  inline PesquisaRow() : PesquisaRow(nullptr) {}
  ~PesquisaRow() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PesquisaRow* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PesquisaRow));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PesquisaRow(::google::protobuf::internal::ConstantInitialized);

  inline PesquisaRow(const PesquisaRow& from) : PesquisaRow(nullptr, from) {}
  inline PesquisaRow(PesquisaRow&& from) noexcept
      : PesquisaRow(nullptr, std::move(from)) {}
  inline PesquisaRow& operator=(const PesquisaRow& from) {
    CopyFrom(from);
    return *this;
  }
  inline PesquisaRow& operator=(PesquisaRow&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PesquisaRow& default_instance() {
    return *reinterpret_cast<const PesquisaRow*>(
        &_PesquisaRow_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PesquisaRow& a, PesquisaRow& b) { a.Swap(&b); }
  inline void Swap(PesquisaRow* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PesquisaRow* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PesquisaRow* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PesquisaRow>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PesquisaRow& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PesquisaRow& from) { PesquisaRow::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PesquisaRow* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "extractor.PesquisaRow"; }

 protected:
  explicit PesquisaRow(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PesquisaRow(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PesquisaRow& from);
  PesquisaRow(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PesquisaRow&& from) noexcept
      : PesquisaRow(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCidadeOrigemFieldNumber = 1,
    kCidadeDestinoFieldNumber = 2,
    kNomeHotelFieldNumber = 3,
    kDataIdaDiaFieldNumber = 4,
    kDataIdaMesFieldNumber = 5,
    kDataIdaAnoFieldNumber = 6,
    kDataVoltaDiaFieldNumber = 7,
    kDataVoltaMesFieldNumber = 8,
    kDataVoltaAnoFieldNumber = 9,
  };
  // string cidade_origem = 1;
  void clear_cidade_origem() ;
  const std::string& cidade_origem() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cidade_origem(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_cidade_origem();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_cidade_origem();
  void set_allocated_cidade_origem(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_cidade_origem() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cidade_origem(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_cidade_origem();

  public:
  // string cidade_destino = 2;
  void clear_cidade_destino() ;
  const std::string& cidade_destino() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cidade_destino(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_cidade_destino();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_cidade_destino();
  void set_allocated_cidade_destino(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_cidade_destino() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cidade_destino(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_cidade_destino();

  public:
  // string nome_hotel = 3;
  void clear_nome_hotel() ;
  const std::string& nome_hotel() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_nome_hotel(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_nome_hotel();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_nome_hotel();
  void set_allocated_nome_hotel(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_nome_hotel() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nome_hotel(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_nome_hotel();

  public:
  // int32 data_ida_dia = 4;
  void clear_data_ida_dia() ;
  ::int32_t data_ida_dia() const;
  void set_data_ida_dia(::int32_t value);

  private:
  ::int32_t _internal_data_ida_dia() const;
  void _internal_set_data_ida_dia(::int32_t value);

  public:
  // int32 data_ida_mes = 5;
  void clear_data_ida_mes() ;
  ::int32_t data_ida_mes() const;
  void set_data_ida_mes(::int32_t value);

  private:
  ::int32_t _internal_data_ida_mes() const;
  void _internal_set_data_ida_mes(::int32_t value);

  public:
  // int32 data_ida_ano = 6;
  void clear_data_ida_ano() ;
  ::int32_t data_ida_ano() const;
  void set_data_ida_ano(::int32_t value);

  private:
  ::int32_t _internal_data_ida_ano() const;
  void _internal_set_data_ida_ano(::int32_t value);

  public:
  // int32 data_volta_dia = 7;
  void clear_data_volta_dia() ;
  ::int32_t data_volta_dia() const;
  void set_data_volta_dia(::int32_t value);

  private:
  ::int32_t _internal_data_volta_dia() const;
  void _internal_set_data_volta_dia(::int32_t value);

  public:
  // int32 data_volta_mes = 8;
  void clear_data_volta_mes() ;
  ::int32_t data_volta_mes() const;
  void set_data_volta_mes(::int32_t value);

  private:
  ::int32_t _internal_data_volta_mes() const;
  void _internal_set_data_volta_mes(::int32_t value);

  public:
  // int32 data_volta_ano = 9;
  void clear_data_volta_ano() ;
  ::int32_t data_volta_ano() const;
  void set_data_volta_ano(::int32_t value);

  private:
  ::int32_t _internal_data_volta_ano() const;
  void _internal_set_data_volta_ano(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:extractor.PesquisaRow)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 9,
                                   0, 75,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PesquisaRow& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr cidade_origem_;
    ::google::protobuf::internal::ArenaStringPtr cidade_destino_;
    ::google::protobuf::internal::ArenaStringPtr nome_hotel_;
    ::int32_t data_ida_dia_;
    ::int32_t data_ida_mes_;
    ::int32_t data_ida_ano_;
    ::int32_t data_volta_dia_;
    ::int32_t data_volta_mes_;
    ::int32_t data_volta_ano_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_extractor_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PesquisaRow_class_data_;
// -------------------------------------------------------------------

class FlightRow final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:extractor.FlightRow) */ {
 public:
  inline FlightRow() : FlightRow(nullptr) {}
  ~FlightRow() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FlightRow* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FlightRow));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FlightRow(::google::protobuf::internal::ConstantInitialized);

  inline FlightRow(const FlightRow& from) : FlightRow(nullptr, from) {}
  inline FlightRow(FlightRow&& from) noexcept
      : FlightRow(nullptr, std::move(from)) {}
  inline FlightRow& operator=(const FlightRow& from) {
    CopyFrom(from);
    return *this;
  }
  inline FlightRow& operator=(FlightRow&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FlightRow& default_instance() {
    return *reinterpret_cast<const FlightRow*>(
        &_FlightRow_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(FlightRow& a, FlightRow& b) { a.Swap(&b); }
  inline void Swap(FlightRow* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FlightRow* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FlightRow* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FlightRow>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FlightRow& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FlightRow& from) { FlightRow::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FlightRow* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "extractor.FlightRow"; }

 protected:
  explicit FlightRow(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FlightRow(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FlightRow& from);
  FlightRow(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FlightRow&& from) noexcept
      : FlightRow(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCidadeOrigemFieldNumber = 1,
    kCidadeDestinoFieldNumber = 2,
    kAssentosOcupadosFieldNumber = 3,
    kAssentosTotaisFieldNumber = 4,
    kAssentosDisponiveisFieldNumber = 5,
    kDiaFieldNumber = 6,
    kMesFieldNumber = 7,
    kAnoFieldNumber = 8,
  };
  // string cidade_origem = 1;
  void clear_cidade_origem() ;
  const std::string& cidade_origem() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cidade_origem(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_cidade_origem();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_cidade_origem();
  void set_allocated_cidade_origem(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_cidade_origem() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cidade_origem(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_cidade_origem();

  public:
  // string cidade_destino = 2;
  void clear_cidade_destino() ;
  const std::string& cidade_destino() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cidade_destino(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_cidade_destino();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_cidade_destino();
  void set_allocated_cidade_destino(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_cidade_destino() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cidade_destino(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_cidade_destino();

  public:
  // int32 assentos_ocupados = 3;
  void clear_assentos_ocupados() ;
  ::int32_t assentos_ocupados() const;
  void set_assentos_ocupados(::int32_t value);

  private:
  ::int32_t _internal_assentos_ocupados() const;
  void _internal_set_assentos_ocupados(::int32_t value);

  public:
  // int32 assentos_totais = 4;
  void clear_assentos_totais() ;
  ::int32_t assentos_totais() const;
  void set_assentos_totais(::int32_t value);

  private:
  ::int32_t _internal_assentos_totais() const;
  void _internal_set_assentos_totais(::int32_t value);

  public:
  // int32 assentos_disponiveis = 5;
  void clear_assentos_disponiveis() ;
  ::int32_t assentos_disponiveis() const;
  void set_assentos_disponiveis(::int32_t value);

  private:
  ::int32_t _internal_assentos_disponiveis() const;
  void _internal_set_assentos_disponiveis(::int32_t value);

  public:
  // int32 dia = 6;
  void clear_dia() ;
  ::int32_t dia() const;
  void set_dia(::int32_t value);

  private:
  ::int32_t _internal_dia() const;
  void _internal_set_dia(::int32_t value);

  public:
  // int32 mes = 7;
  void clear_mes() ;
  ::int32_t mes() const;
  void set_mes(::int32_t value);

  private:
  ::int32_t _internal_mes() const;
  void _internal_set_mes(::int32_t value);

  public:
  // int32 ano = 8;
  void clear_ano() ;
  ::int32_t ano() const;
  void set_ano(::int32_t value);

  private:
  ::int32_t _internal_ano() const;
  void _internal_set_ano(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:extractor.FlightRow)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   0, 63,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FlightRow& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr cidade_origem_;
    ::google::protobuf::internal::ArenaStringPtr cidade_destino_;
    ::int32_t assentos_ocupados_;
    ::int32_t assentos_totais_;
    ::int32_t assentos_disponiveis_;
    ::int32_t dia_;
    ::int32_t mes_;
    ::int32_t ano_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_extractor_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FlightRow_class_data_;
// -------------------------------------------------------------------

class AllDataResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:extractor.AllDataResponse) */ {
 public:
  inline AllDataResponse() : AllDataResponse(nullptr) {}
  ~AllDataResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AllDataResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AllDataResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AllDataResponse(::google::protobuf::internal::ConstantInitialized);

  inline AllDataResponse(const AllDataResponse& from) : AllDataResponse(nullptr, from) {}
  inline AllDataResponse(AllDataResponse&& from) noexcept
      : AllDataResponse(nullptr, std::move(from)) {}
  inline AllDataResponse& operator=(const AllDataResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AllDataResponse& operator=(AllDataResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AllDataResponse& default_instance() {
    return *reinterpret_cast<const AllDataResponse*>(
        &_AllDataResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(AllDataResponse& a, AllDataResponse& b) { a.Swap(&b); }
  inline void Swap(AllDataResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AllDataResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AllDataResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AllDataResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AllDataResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AllDataResponse& from) { AllDataResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AllDataResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "extractor.AllDataResponse"; }

 protected:
  explicit AllDataResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AllDataResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AllDataResponse& from);
  AllDataResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AllDataResponse&& from) noexcept
      : AllDataResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVoosFieldNumber = 1,
    kReservasFieldNumber = 2,
    kPesquisasFieldNumber = 3,
  };
  // repeated .extractor.FlightRow voos = 1;
  int voos_size() const;
  private:
  int _internal_voos_size() const;

  public:
  void clear_voos() ;
  ::extractor::FlightRow* PROTOBUF_NONNULL mutable_voos(int index);
  ::google::protobuf::RepeatedPtrField<::extractor::FlightRow>* PROTOBUF_NONNULL mutable_voos();

  private:
  const ::google::protobuf::RepeatedPtrField<::extractor::FlightRow>& _internal_voos() const;
  ::google::protobuf::RepeatedPtrField<::extractor::FlightRow>* PROTOBUF_NONNULL _internal_mutable_voos();
  public:
  const ::extractor::FlightRow& voos(int index) const;
  ::extractor::FlightRow* PROTOBUF_NONNULL add_voos();
  const ::google::protobuf::RepeatedPtrField<::extractor::FlightRow>& voos() const;
  // repeated .extractor.ReservaRow reservas = 2;
  int reservas_size() const;
  private:
  int _internal_reservas_size() const;

  public:
  void clear_reservas() ;
  ::extractor::ReservaRow* PROTOBUF_NONNULL mutable_reservas(int index);
  ::google::protobuf::RepeatedPtrField<::extractor::ReservaRow>* PROTOBUF_NONNULL mutable_reservas();

  private:
  const ::google::protobuf::RepeatedPtrField<::extractor::ReservaRow>& _internal_reservas() const;
  ::google::protobuf::RepeatedPtrField<::extractor::ReservaRow>* PROTOBUF_NONNULL _internal_mutable_reservas();
  public:
  const ::extractor::ReservaRow& reservas(int index) const;
  ::extractor::ReservaRow* PROTOBUF_NONNULL add_reservas();
  const ::google::protobuf::RepeatedPtrField<::extractor::ReservaRow>& reservas() const;
  // repeated .extractor.PesquisaRow pesquisas = 3;
  int pesquisas_size() const;
  private:
  int _internal_pesquisas_size() const;

  public:
  void clear_pesquisas() ;
  ::extractor::PesquisaRow* PROTOBUF_NONNULL mutable_pesquisas(int index);
  ::google::protobuf::RepeatedPtrField<::extractor::PesquisaRow>* PROTOBUF_NONNULL mutable_pesquisas();

  private:
  const ::google::protobuf::RepeatedPtrField<::extractor::PesquisaRow>& _internal_pesquisas() const;
  ::google::protobuf::RepeatedPtrField<::extractor::PesquisaRow>* PROTOBUF_NONNULL _internal_mutable_pesquisas();
  public:
  const ::extractor::PesquisaRow& pesquisas(int index) const;
  ::extractor::PesquisaRow* PROTOBUF_NONNULL add_pesquisas();
  const ::google::protobuf::RepeatedPtrField<::extractor::PesquisaRow>& pesquisas() const;
  // @@protoc_insertion_point(class_scope:extractor.AllDataResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AllDataResponse& from_msg);
    ::google::protobuf::RepeatedPtrField< ::extractor::FlightRow > voos_;
    ::google::protobuf::RepeatedPtrField< ::extractor::ReservaRow > reservas_;
    ::google::protobuf::RepeatedPtrField< ::extractor::PesquisaRow > pesquisas_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_extractor_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AllDataResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// FlightRow

// string cidade_origem = 1;
inline void FlightRow::clear_cidade_origem() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cidade_origem_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& FlightRow::cidade_origem() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:extractor.FlightRow.cidade_origem)
  return _internal_cidade_origem();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FlightRow::set_cidade_origem(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.cidade_origem_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:extractor.FlightRow.cidade_origem)
}
inline std::string* PROTOBUF_NONNULL FlightRow::mutable_cidade_origem()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cidade_origem();
  // @@protoc_insertion_point(field_mutable:extractor.FlightRow.cidade_origem)
  return _s;
}
inline const std::string& FlightRow::_internal_cidade_origem() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cidade_origem_.Get();
}
inline void FlightRow::_internal_set_cidade_origem(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.cidade_origem_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL FlightRow::_internal_mutable_cidade_origem() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.cidade_origem_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE FlightRow::release_cidade_origem() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:extractor.FlightRow.cidade_origem)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.cidade_origem_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cidade_origem_.Set("", GetArena());
  }
  return released;
}
inline void FlightRow::set_allocated_cidade_origem(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.cidade_origem_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cidade_origem_.IsDefault()) {
    _impl_.cidade_origem_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:extractor.FlightRow.cidade_origem)
}

// string cidade_destino = 2;
inline void FlightRow::clear_cidade_destino() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cidade_destino_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& FlightRow::cidade_destino() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:extractor.FlightRow.cidade_destino)
  return _internal_cidade_destino();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FlightRow::set_cidade_destino(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.cidade_destino_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:extractor.FlightRow.cidade_destino)
}
inline std::string* PROTOBUF_NONNULL FlightRow::mutable_cidade_destino()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cidade_destino();
  // @@protoc_insertion_point(field_mutable:extractor.FlightRow.cidade_destino)
  return _s;
}
inline const std::string& FlightRow::_internal_cidade_destino() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cidade_destino_.Get();
}
inline void FlightRow::_internal_set_cidade_destino(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.cidade_destino_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL FlightRow::_internal_mutable_cidade_destino() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.cidade_destino_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE FlightRow::release_cidade_destino() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:extractor.FlightRow.cidade_destino)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.cidade_destino_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cidade_destino_.Set("", GetArena());
  }
  return released;
}
inline void FlightRow::set_allocated_cidade_destino(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.cidade_destino_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cidade_destino_.IsDefault()) {
    _impl_.cidade_destino_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:extractor.FlightRow.cidade_destino)
}

// int32 assentos_ocupados = 3;
inline void FlightRow::clear_assentos_ocupados() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.assentos_ocupados_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t FlightRow::assentos_ocupados() const {
  // @@protoc_insertion_point(field_get:extractor.FlightRow.assentos_ocupados)
  return _internal_assentos_ocupados();
}
inline void FlightRow::set_assentos_ocupados(::int32_t value) {
  _internal_set_assentos_ocupados(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:extractor.FlightRow.assentos_ocupados)
}
inline ::int32_t FlightRow::_internal_assentos_ocupados() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.assentos_ocupados_;
}
inline void FlightRow::_internal_set_assentos_ocupados(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.assentos_ocupados_ = value;
}

// int32 assentos_totais = 4;
inline void FlightRow::clear_assentos_totais() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.assentos_totais_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t FlightRow::assentos_totais() const {
  // @@protoc_insertion_point(field_get:extractor.FlightRow.assentos_totais)
  return _internal_assentos_totais();
}
inline void FlightRow::set_assentos_totais(::int32_t value) {
  _internal_set_assentos_totais(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:extractor.FlightRow.assentos_totais)
}
inline ::int32_t FlightRow::_internal_assentos_totais() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.assentos_totais_;
}
inline void FlightRow::_internal_set_assentos_totais(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.assentos_totais_ = value;
}

// int32 assentos_disponiveis = 5;
inline void FlightRow::clear_assentos_disponiveis() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.assentos_disponiveis_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t FlightRow::assentos_disponiveis() const {
  // @@protoc_insertion_point(field_get:extractor.FlightRow.assentos_disponiveis)
  return _internal_assentos_disponiveis();
}
inline void FlightRow::set_assentos_disponiveis(::int32_t value) {
  _internal_set_assentos_disponiveis(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:extractor.FlightRow.assentos_disponiveis)
}
inline ::int32_t FlightRow::_internal_assentos_disponiveis() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.assentos_disponiveis_;
}
inline void FlightRow::_internal_set_assentos_disponiveis(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.assentos_disponiveis_ = value;
}

// int32 dia = 6;
inline void FlightRow::clear_dia() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dia_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t FlightRow::dia() const {
  // @@protoc_insertion_point(field_get:extractor.FlightRow.dia)
  return _internal_dia();
}
inline void FlightRow::set_dia(::int32_t value) {
  _internal_set_dia(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:extractor.FlightRow.dia)
}
inline ::int32_t FlightRow::_internal_dia() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dia_;
}
inline void FlightRow::_internal_set_dia(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dia_ = value;
}

// int32 mes = 7;
inline void FlightRow::clear_mes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mes_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::int32_t FlightRow::mes() const {
  // @@protoc_insertion_point(field_get:extractor.FlightRow.mes)
  return _internal_mes();
}
inline void FlightRow::set_mes(::int32_t value) {
  _internal_set_mes(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:extractor.FlightRow.mes)
}
inline ::int32_t FlightRow::_internal_mes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mes_;
}
inline void FlightRow::_internal_set_mes(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mes_ = value;
}

// int32 ano = 8;
inline void FlightRow::clear_ano() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ano_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::int32_t FlightRow::ano() const {
  // @@protoc_insertion_point(field_get:extractor.FlightRow.ano)
  return _internal_ano();
}
inline void FlightRow::set_ano(::int32_t value) {
  _internal_set_ano(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:extractor.FlightRow.ano)
}
inline ::int32_t FlightRow::_internal_ano() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ano_;
}
inline void FlightRow::_internal_set_ano(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ano_ = value;
}

// -------------------------------------------------------------------

// ReservaRow

// string tipo_quarto = 1;
inline void ReservaRow::clear_tipo_quarto() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tipo_quarto_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ReservaRow::tipo_quarto() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:extractor.ReservaRow.tipo_quarto)
  return _internal_tipo_quarto();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ReservaRow::set_tipo_quarto(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.tipo_quarto_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:extractor.ReservaRow.tipo_quarto)
}
inline std::string* PROTOBUF_NONNULL ReservaRow::mutable_tipo_quarto()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_tipo_quarto();
  // @@protoc_insertion_point(field_mutable:extractor.ReservaRow.tipo_quarto)
  return _s;
}
inline const std::string& ReservaRow::_internal_tipo_quarto() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tipo_quarto_.Get();
}
inline void ReservaRow::_internal_set_tipo_quarto(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.tipo_quarto_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL ReservaRow::_internal_mutable_tipo_quarto() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.tipo_quarto_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE ReservaRow::release_tipo_quarto() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:extractor.ReservaRow.tipo_quarto)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.tipo_quarto_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.tipo_quarto_.Set("", GetArena());
  }
  return released;
}
inline void ReservaRow::set_allocated_tipo_quarto(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.tipo_quarto_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.tipo_quarto_.IsDefault()) {
    _impl_.tipo_quarto_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:extractor.ReservaRow.tipo_quarto)
}

// string nome_hotel = 2;
inline void ReservaRow::clear_nome_hotel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nome_hotel_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ReservaRow::nome_hotel() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:extractor.ReservaRow.nome_hotel)
  return _internal_nome_hotel();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ReservaRow::set_nome_hotel(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.nome_hotel_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:extractor.ReservaRow.nome_hotel)
}
inline std::string* PROTOBUF_NONNULL ReservaRow::mutable_nome_hotel()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_nome_hotel();
  // @@protoc_insertion_point(field_mutable:extractor.ReservaRow.nome_hotel)
  return _s;
}
inline const std::string& ReservaRow::_internal_nome_hotel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nome_hotel_.Get();
}
inline void ReservaRow::_internal_set_nome_hotel(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.nome_hotel_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL ReservaRow::_internal_mutable_nome_hotel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.nome_hotel_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE ReservaRow::release_nome_hotel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:extractor.ReservaRow.nome_hotel)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.nome_hotel_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nome_hotel_.Set("", GetArena());
  }
  return released;
}
inline void ReservaRow::set_allocated_nome_hotel(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.nome_hotel_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nome_hotel_.IsDefault()) {
    _impl_.nome_hotel_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:extractor.ReservaRow.nome_hotel)
}

// string cidade_destino = 3;
inline void ReservaRow::clear_cidade_destino() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cidade_destino_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ReservaRow::cidade_destino() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:extractor.ReservaRow.cidade_destino)
  return _internal_cidade_destino();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ReservaRow::set_cidade_destino(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.cidade_destino_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:extractor.ReservaRow.cidade_destino)
}
inline std::string* PROTOBUF_NONNULL ReservaRow::mutable_cidade_destino()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cidade_destino();
  // @@protoc_insertion_point(field_mutable:extractor.ReservaRow.cidade_destino)
  return _s;
}
inline const std::string& ReservaRow::_internal_cidade_destino() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cidade_destino_.Get();
}
inline void ReservaRow::_internal_set_cidade_destino(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.cidade_destino_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL ReservaRow::_internal_mutable_cidade_destino() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.cidade_destino_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE ReservaRow::release_cidade_destino() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:extractor.ReservaRow.cidade_destino)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.cidade_destino_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cidade_destino_.Set("", GetArena());
  }
  return released;
}
inline void ReservaRow::set_allocated_cidade_destino(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.cidade_destino_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cidade_destino_.IsDefault()) {
    _impl_.cidade_destino_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:extractor.ReservaRow.cidade_destino)
}

// int32 numero_quarto = 4;
inline void ReservaRow::clear_numero_quarto() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numero_quarto_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t ReservaRow::numero_quarto() const {
  // @@protoc_insertion_point(field_get:extractor.ReservaRow.numero_quarto)
  return _internal_numero_quarto();
}
inline void ReservaRow::set_numero_quarto(::int32_t value) {
  _internal_set_numero_quarto(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:extractor.ReservaRow.numero_quarto)
}
inline ::int32_t ReservaRow::_internal_numero_quarto() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numero_quarto_;
}
inline void ReservaRow::_internal_set_numero_quarto(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numero_quarto_ = value;
}

// int32 quantidade_pessoas = 5;
inline void ReservaRow::clear_quantidade_pessoas() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quantidade_pessoas_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t ReservaRow::quantidade_pessoas() const {
  // @@protoc_insertion_point(field_get:extractor.ReservaRow.quantidade_pessoas)
  return _internal_quantidade_pessoas();
}
inline void ReservaRow::set_quantidade_pessoas(::int32_t value) {
  _internal_set_quantidade_pessoas(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:extractor.ReservaRow.quantidade_pessoas)
}
inline ::int32_t ReservaRow::_internal_quantidade_pessoas() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.quantidade_pessoas_;
}
inline void ReservaRow::_internal_set_quantidade_pessoas(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quantidade_pessoas_ = value;
}

// float preco = 6;
inline void ReservaRow::clear_preco() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.preco_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline float ReservaRow::preco() const {
  // @@protoc_insertion_point(field_get:extractor.ReservaRow.preco)
  return _internal_preco();
}
inline void ReservaRow::set_preco(float value) {
  _internal_set_preco(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:extractor.ReservaRow.preco)
}
inline float ReservaRow::_internal_preco() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.preco_;
}
inline void ReservaRow::_internal_set_preco(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.preco_ = value;
}

// bool ocupado = 7;
inline void ReservaRow::clear_ocupado() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ocupado_ = false;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline bool ReservaRow::ocupado() const {
  // @@protoc_insertion_point(field_get:extractor.ReservaRow.ocupado)
  return _internal_ocupado();
}
inline void ReservaRow::set_ocupado(bool value) {
  _internal_set_ocupado(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:extractor.ReservaRow.ocupado)
}
inline bool ReservaRow::_internal_ocupado() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ocupado_;
}
inline void ReservaRow::_internal_set_ocupado(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ocupado_ = value;
}

// int32 data_ida_dia = 8;
inline void ReservaRow::clear_data_ida_dia() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ida_dia_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::int32_t ReservaRow::data_ida_dia() const {
  // @@protoc_insertion_point(field_get:extractor.ReservaRow.data_ida_dia)
  return _internal_data_ida_dia();
}
inline void ReservaRow::set_data_ida_dia(::int32_t value) {
  _internal_set_data_ida_dia(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:extractor.ReservaRow.data_ida_dia)
}
inline ::int32_t ReservaRow::_internal_data_ida_dia() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_ida_dia_;
}
inline void ReservaRow::_internal_set_data_ida_dia(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ida_dia_ = value;
}

// int32 data_ida_mes = 9;
inline void ReservaRow::clear_data_ida_mes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ida_mes_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline ::int32_t ReservaRow::data_ida_mes() const {
  // @@protoc_insertion_point(field_get:extractor.ReservaRow.data_ida_mes)
  return _internal_data_ida_mes();
}
inline void ReservaRow::set_data_ida_mes(::int32_t value) {
  _internal_set_data_ida_mes(value);
  _impl_._has_bits_[0] |= 0x00000100u;
  // @@protoc_insertion_point(field_set:extractor.ReservaRow.data_ida_mes)
}
inline ::int32_t ReservaRow::_internal_data_ida_mes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_ida_mes_;
}
inline void ReservaRow::_internal_set_data_ida_mes(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ida_mes_ = value;
}

// int32 data_ida_ano = 10;
inline void ReservaRow::clear_data_ida_ano() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ida_ano_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline ::int32_t ReservaRow::data_ida_ano() const {
  // @@protoc_insertion_point(field_get:extractor.ReservaRow.data_ida_ano)
  return _internal_data_ida_ano();
}
inline void ReservaRow::set_data_ida_ano(::int32_t value) {
  _internal_set_data_ida_ano(value);
  _impl_._has_bits_[0] |= 0x00000200u;
  // @@protoc_insertion_point(field_set:extractor.ReservaRow.data_ida_ano)
}
inline ::int32_t ReservaRow::_internal_data_ida_ano() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_ida_ano_;
}
inline void ReservaRow::_internal_set_data_ida_ano(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ida_ano_ = value;
}

// -------------------------------------------------------------------

// PesquisaRow

// string cidade_origem = 1;
inline void PesquisaRow::clear_cidade_origem() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cidade_origem_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PesquisaRow::cidade_origem() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:extractor.PesquisaRow.cidade_origem)
  return _internal_cidade_origem();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PesquisaRow::set_cidade_origem(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.cidade_origem_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:extractor.PesquisaRow.cidade_origem)
}
inline std::string* PROTOBUF_NONNULL PesquisaRow::mutable_cidade_origem()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cidade_origem();
  // @@protoc_insertion_point(field_mutable:extractor.PesquisaRow.cidade_origem)
  return _s;
}
inline const std::string& PesquisaRow::_internal_cidade_origem() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cidade_origem_.Get();
}
inline void PesquisaRow::_internal_set_cidade_origem(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.cidade_origem_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL PesquisaRow::_internal_mutable_cidade_origem() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.cidade_origem_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE PesquisaRow::release_cidade_origem() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:extractor.PesquisaRow.cidade_origem)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.cidade_origem_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cidade_origem_.Set("", GetArena());
  }
  return released;
}
inline void PesquisaRow::set_allocated_cidade_origem(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.cidade_origem_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cidade_origem_.IsDefault()) {
    _impl_.cidade_origem_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:extractor.PesquisaRow.cidade_origem)
}

// string cidade_destino = 2;
inline void PesquisaRow::clear_cidade_destino() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cidade_destino_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& PesquisaRow::cidade_destino() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:extractor.PesquisaRow.cidade_destino)
  return _internal_cidade_destino();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PesquisaRow::set_cidade_destino(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.cidade_destino_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:extractor.PesquisaRow.cidade_destino)
}
inline std::string* PROTOBUF_NONNULL PesquisaRow::mutable_cidade_destino()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cidade_destino();
  // @@protoc_insertion_point(field_mutable:extractor.PesquisaRow.cidade_destino)
  return _s;
}
inline const std::string& PesquisaRow::_internal_cidade_destino() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cidade_destino_.Get();
}
inline void PesquisaRow::_internal_set_cidade_destino(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.cidade_destino_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL PesquisaRow::_internal_mutable_cidade_destino() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.cidade_destino_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE PesquisaRow::release_cidade_destino() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:extractor.PesquisaRow.cidade_destino)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.cidade_destino_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cidade_destino_.Set("", GetArena());
  }
  return released;
}
inline void PesquisaRow::set_allocated_cidade_destino(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.cidade_destino_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cidade_destino_.IsDefault()) {
    _impl_.cidade_destino_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:extractor.PesquisaRow.cidade_destino)
}

// string nome_hotel = 3;
inline void PesquisaRow::clear_nome_hotel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nome_hotel_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& PesquisaRow::nome_hotel() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:extractor.PesquisaRow.nome_hotel)
  return _internal_nome_hotel();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PesquisaRow::set_nome_hotel(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.nome_hotel_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:extractor.PesquisaRow.nome_hotel)
}
inline std::string* PROTOBUF_NONNULL PesquisaRow::mutable_nome_hotel()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_nome_hotel();
  // @@protoc_insertion_point(field_mutable:extractor.PesquisaRow.nome_hotel)
  return _s;
}
inline const std::string& PesquisaRow::_internal_nome_hotel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nome_hotel_.Get();
}
inline void PesquisaRow::_internal_set_nome_hotel(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.nome_hotel_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL PesquisaRow::_internal_mutable_nome_hotel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.nome_hotel_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE PesquisaRow::release_nome_hotel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:extractor.PesquisaRow.nome_hotel)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.nome_hotel_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nome_hotel_.Set("", GetArena());
  }
  return released;
}
inline void PesquisaRow::set_allocated_nome_hotel(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.nome_hotel_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nome_hotel_.IsDefault()) {
    _impl_.nome_hotel_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:extractor.PesquisaRow.nome_hotel)
}

// int32 data_ida_dia = 4;
inline void PesquisaRow::clear_data_ida_dia() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ida_dia_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t PesquisaRow::data_ida_dia() const {
  // @@protoc_insertion_point(field_get:extractor.PesquisaRow.data_ida_dia)
  return _internal_data_ida_dia();
}
inline void PesquisaRow::set_data_ida_dia(::int32_t value) {
  _internal_set_data_ida_dia(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:extractor.PesquisaRow.data_ida_dia)
}
inline ::int32_t PesquisaRow::_internal_data_ida_dia() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_ida_dia_;
}
inline void PesquisaRow::_internal_set_data_ida_dia(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ida_dia_ = value;
}

// int32 data_ida_mes = 5;
inline void PesquisaRow::clear_data_ida_mes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ida_mes_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t PesquisaRow::data_ida_mes() const {
  // @@protoc_insertion_point(field_get:extractor.PesquisaRow.data_ida_mes)
  return _internal_data_ida_mes();
}
inline void PesquisaRow::set_data_ida_mes(::int32_t value) {
  _internal_set_data_ida_mes(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:extractor.PesquisaRow.data_ida_mes)
}
inline ::int32_t PesquisaRow::_internal_data_ida_mes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_ida_mes_;
}
inline void PesquisaRow::_internal_set_data_ida_mes(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ida_mes_ = value;
}

// int32 data_ida_ano = 6;
inline void PesquisaRow::clear_data_ida_ano() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ida_ano_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t PesquisaRow::data_ida_ano() const {
  // @@protoc_insertion_point(field_get:extractor.PesquisaRow.data_ida_ano)
  return _internal_data_ida_ano();
}
inline void PesquisaRow::set_data_ida_ano(::int32_t value) {
  _internal_set_data_ida_ano(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:extractor.PesquisaRow.data_ida_ano)
}
inline ::int32_t PesquisaRow::_internal_data_ida_ano() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_ida_ano_;
}
inline void PesquisaRow::_internal_set_data_ida_ano(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ida_ano_ = value;
}

// int32 data_volta_dia = 7;
inline void PesquisaRow::clear_data_volta_dia() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_volta_dia_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::int32_t PesquisaRow::data_volta_dia() const {
  // @@protoc_insertion_point(field_get:extractor.PesquisaRow.data_volta_dia)
  return _internal_data_volta_dia();
}
inline void PesquisaRow::set_data_volta_dia(::int32_t value) {
  _internal_set_data_volta_dia(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:extractor.PesquisaRow.data_volta_dia)
}
inline ::int32_t PesquisaRow::_internal_data_volta_dia() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_volta_dia_;
}
inline void PesquisaRow::_internal_set_data_volta_dia(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_volta_dia_ = value;
}

// int32 data_volta_mes = 8;
inline void PesquisaRow::clear_data_volta_mes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_volta_mes_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::int32_t PesquisaRow::data_volta_mes() const {
  // @@protoc_insertion_point(field_get:extractor.PesquisaRow.data_volta_mes)
  return _internal_data_volta_mes();
}
inline void PesquisaRow::set_data_volta_mes(::int32_t value) {
  _internal_set_data_volta_mes(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:extractor.PesquisaRow.data_volta_mes)
}
inline ::int32_t PesquisaRow::_internal_data_volta_mes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_volta_mes_;
}
inline void PesquisaRow::_internal_set_data_volta_mes(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_volta_mes_ = value;
}

// int32 data_volta_ano = 9;
inline void PesquisaRow::clear_data_volta_ano() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_volta_ano_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline ::int32_t PesquisaRow::data_volta_ano() const {
  // @@protoc_insertion_point(field_get:extractor.PesquisaRow.data_volta_ano)
  return _internal_data_volta_ano();
}
inline void PesquisaRow::set_data_volta_ano(::int32_t value) {
  _internal_set_data_volta_ano(value);
  _impl_._has_bits_[0] |= 0x00000100u;
  // @@protoc_insertion_point(field_set:extractor.PesquisaRow.data_volta_ano)
}
inline ::int32_t PesquisaRow::_internal_data_volta_ano() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_volta_ano_;
}
inline void PesquisaRow::_internal_set_data_volta_ano(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_volta_ano_ = value;
}

// -------------------------------------------------------------------

// AllDataResponse

// repeated .extractor.FlightRow voos = 1;
inline int AllDataResponse::_internal_voos_size() const {
  return _internal_voos().size();
}
inline int AllDataResponse::voos_size() const {
  return _internal_voos_size();
}
inline void AllDataResponse::clear_voos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.voos_.Clear();
}
inline ::extractor::FlightRow* PROTOBUF_NONNULL AllDataResponse::mutable_voos(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:extractor.AllDataResponse.voos)
  return _internal_mutable_voos()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::extractor::FlightRow>* PROTOBUF_NONNULL AllDataResponse::mutable_voos()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:extractor.AllDataResponse.voos)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_voos();
}
inline const ::extractor::FlightRow& AllDataResponse::voos(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:extractor.AllDataResponse.voos)
  return _internal_voos().Get(index);
}
inline ::extractor::FlightRow* PROTOBUF_NONNULL AllDataResponse::add_voos()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::extractor::FlightRow* _add = _internal_mutable_voos()->Add();
  // @@protoc_insertion_point(field_add:extractor.AllDataResponse.voos)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::extractor::FlightRow>& AllDataResponse::voos() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:extractor.AllDataResponse.voos)
  return _internal_voos();
}
inline const ::google::protobuf::RepeatedPtrField<::extractor::FlightRow>&
AllDataResponse::_internal_voos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.voos_;
}
inline ::google::protobuf::RepeatedPtrField<::extractor::FlightRow>* PROTOBUF_NONNULL
AllDataResponse::_internal_mutable_voos() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.voos_;
}

// repeated .extractor.ReservaRow reservas = 2;
inline int AllDataResponse::_internal_reservas_size() const {
  return _internal_reservas().size();
}
inline int AllDataResponse::reservas_size() const {
  return _internal_reservas_size();
}
inline void AllDataResponse::clear_reservas() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reservas_.Clear();
}
inline ::extractor::ReservaRow* PROTOBUF_NONNULL AllDataResponse::mutable_reservas(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:extractor.AllDataResponse.reservas)
  return _internal_mutable_reservas()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::extractor::ReservaRow>* PROTOBUF_NONNULL AllDataResponse::mutable_reservas()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:extractor.AllDataResponse.reservas)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_reservas();
}
inline const ::extractor::ReservaRow& AllDataResponse::reservas(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:extractor.AllDataResponse.reservas)
  return _internal_reservas().Get(index);
}
inline ::extractor::ReservaRow* PROTOBUF_NONNULL AllDataResponse::add_reservas()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::extractor::ReservaRow* _add = _internal_mutable_reservas()->Add();
  // @@protoc_insertion_point(field_add:extractor.AllDataResponse.reservas)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::extractor::ReservaRow>& AllDataResponse::reservas() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:extractor.AllDataResponse.reservas)
  return _internal_reservas();
}
inline const ::google::protobuf::RepeatedPtrField<::extractor::ReservaRow>&
AllDataResponse::_internal_reservas() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reservas_;
}
inline ::google::protobuf::RepeatedPtrField<::extractor::ReservaRow>* PROTOBUF_NONNULL
AllDataResponse::_internal_mutable_reservas() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.reservas_;
}

// repeated .extractor.PesquisaRow pesquisas = 3;
inline int AllDataResponse::_internal_pesquisas_size() const {
  return _internal_pesquisas().size();
}
inline int AllDataResponse::pesquisas_size() const {
  return _internal_pesquisas_size();
}
inline void AllDataResponse::clear_pesquisas() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pesquisas_.Clear();
}
inline ::extractor::PesquisaRow* PROTOBUF_NONNULL AllDataResponse::mutable_pesquisas(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:extractor.AllDataResponse.pesquisas)
  return _internal_mutable_pesquisas()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::extractor::PesquisaRow>* PROTOBUF_NONNULL AllDataResponse::mutable_pesquisas()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:extractor.AllDataResponse.pesquisas)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pesquisas();
}
inline const ::extractor::PesquisaRow& AllDataResponse::pesquisas(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:extractor.AllDataResponse.pesquisas)
  return _internal_pesquisas().Get(index);
}
inline ::extractor::PesquisaRow* PROTOBUF_NONNULL AllDataResponse::add_pesquisas()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::extractor::PesquisaRow* _add = _internal_mutable_pesquisas()->Add();
  // @@protoc_insertion_point(field_add:extractor.AllDataResponse.pesquisas)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::extractor::PesquisaRow>& AllDataResponse::pesquisas() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:extractor.AllDataResponse.pesquisas)
  return _internal_pesquisas();
}
inline const ::google::protobuf::RepeatedPtrField<::extractor::PesquisaRow>&
AllDataResponse::_internal_pesquisas() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pesquisas_;
}
inline ::google::protobuf::RepeatedPtrField<::extractor::PesquisaRow>* PROTOBUF_NONNULL
AllDataResponse::_internal_mutable_pesquisas() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pesquisas_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace extractor


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // extractor_2eproto_2epb_2eh
